import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author Hayden Cummins
 *
 */
public final class RSSAggregator {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSAggregator() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html> <head> <title>the channel tag title as the page title</title>
     * </head> <body>
     * <h1>the page title inside a link to the <channel> link</h1>
     * <p>
     * the channel description
     * </p>
     * <table border="1">
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel") : ""
                + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        String titlchildtext = "";

        titlchildtext = channel.child(getChildElement(channel, "title"))
                .child(0).label();
        String descchildtext = "";
        if (channel.child(getChildElement(channel, "description"))
                .numberOfChildren() < 0) {
            descchildtext = "No Description.";
        } else if (channel.child(getChildElement(channel, "description"))
                .numberOfChildren() > 0) {
            descchildtext = channel
                    .child(getChildElement(channel, "description")).child(0)
                    .label();
        }
        out.println("<html>");
        out.println("<head>");
        out.println("<title>" + titlchildtext + "</title>");
        out.println("</head>");
        out.println("<body>");
        out.println(
                "<h1><a href=\""
                        + channel.child(getChildElement(channel, "link"))
                                .child(0).label()
                        + "\">" + titlchildtext + "</a></h1>");
        out.println("<p>" + descchildtext + "</p>");
        out.println("<table border=\"1\">");
        out.println("<tr>");
        out.println("<th>Date</th>");
        out.println("<th>Source</th>");
        out.println("<th>News</th>");
        out.println("</tr>");

        int x = 0;
        while (channel.numberOfChildren() > x) {
            if (channel.child(x).label().equals("item")) {
                processItem(channel.child(x), out);
            }
            x++;
        }

    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * </table>
     * </body> </html>
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("</table>");
        out.println("</body>");
        out.println("</html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        int taglocation = -1;
        if (xml.hasAttribute(tag)) {
            int i = 0;
            while (i < xml.numberOfChildren() && taglocation < 0) {
                if (xml.child(i).label().equals(tag)) {
                    taglocation = i;
                }
                i++;
            }
        }
        return taglocation;
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item") : ""
                + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("<tr>");
        int n = getChildElement(item, "pubDate");
        if (n == -1) {
            out.println("<td>No date available</td>");
        } else {
            String pubDateContent = item.child(n).child(0).label();
            out.println("<td>" + pubDateContent + "</td>");
        }
        n = getChildElement(item, "source");
        if (n == -1) {
            out.println("<td>No source available</td>");
        } else if (item.child(n).numberOfChildren() > 0) {
            String url = item.child(n).attributeValue("url");
            String sourceContent = item.child(n).child(0).label();
            out.println(
                    "<td><a href = " + url + ">" + sourceContent + "</a></td>");
        }
        n = getChildElement(item, "title");
        if (n == -1) {
            if (item.child(n).numberOfChildren() > 0) {
                n = getChildElement(item, "description");
                String descriptionContent = item.child(n).child(0).label();
                n = getChildElement(item, "link");
                if (n == -1) {
                    out.println("<td>" + descriptionContent + "</td>");
                } else if (item.child(n).numberOfChildren() > 0) {
                    String url = item.child(n).child(0).label();
                    out.println("<td><a href = " + url + ">"
                            + descriptionContent + "</a></td>");
                }
            }
        } else if (item.child(n).numberOfChildren() > 0) {
            String titleContent = item.child(n).child(0).label();
            n = getChildElement(item, "link");
            if (n == -1) {
                out.println("<td>" + titleContent + "</td>");
            } else if (item.child(n).numberOfChildren() > 0) {
                String url = item.child(n).child(0).label();
                out.println("<td><a href = " + url + ">" + titleContent
                        + "</a></td>");
            }
        }
        out.println("</tr>");

    }

    /**
     * Processes one XML RSS (version 2.0) feed from a given URL converting it
     * into the corresponding HTML output file.
     *
     * @param url
     *            the URL of the RSS feed
     * @param file
     *            the name of the HTML output file
     * @param out
     *            the output stream to report progress or errors
     * @updates out.content
     * @requires out.is_open
     * @ensures <pre>
     * [reads RSS feed from url, saves HTML document with table of news items
     *   to file, appends to out.content any needed messages]
     * </pre>
     */
    private static void processFeed(String url, String file, SimpleWriter out) {

        XMLTree xml = new XMLTree1(url);

        SimpleWriter fileOut = new SimpleWriter1L(file);

        outputHeader(xml.child(0), fileOut);
        outputFooter(fileOut);

    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        out.print("Enter feed list: ");
        String inputfeedURL = in.nextLine();
        XMLTree xml = new XMLTree1(inputfeedURL);
        xml.display();

        out.print("Please name the output file: ");
        String outfileName = in.nextLine();

        int i = 0;
        while (i < xml.numberOfChildren()) {
            String url = xml.child(i).attributeValue("url");
            String fileOut = "out" + (i + 1);
            processFeed(url, fileOut, out);
            i++;
        }

        /*
         * while (!xml.label().equals("rss") && !xml.hasAttribute("version") &&
         * !xml.attributeValue("version").equals("2.0")) {
         * out.print("\n Enter a valid URL of a RSS 2.0 feed: "); inputfeedURL =
         * in.nextLine(); xml = new XMLTree1(inputfeedURL); }
         */

        SimpleWriter fileOut = new SimpleWriter1L(outfileName);

        outputHeader(xml.child(0), fileOut);
        outputFooter(fileOut);

        in.close();
        out.close();
    }

}